config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :favoritos
  resources :categoria
  root  'publico/empresas#index'

  namespace :publico do
    resources :clientes
    resources :empresas
    resources :produtos
    resources :ambientes
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ambiente.rb
class Ambiente < ApplicationRecord
end

app/models/publico/ambiente.rb
class Publico::Ambiente < ApplicationRecord
end

app/controllers/ambientes_controller.rb
class Publico::AmbientesController < ApplicationController
  before_action :set_ambiente, only: [:show, :edit, :update, :destroy]

  # GET /ambientes
  # GET /ambientes.json
  def index
    @ambientes = Ambiente.all
  end

  # GET /ambientes/1
  # GET /ambientes/1.json
  def show
  end

  # GET /ambientes/new
  def new
    @ambiente = Ambiente.new
  end

  # GET /ambientes/1/edit
  def edit
  end

  # POST /ambientes
  # POST /ambientes.json
  def create
    @ambiente = Ambiente.new(ambiente_params)

    respond_to do |format|
      if @ambiente.save
        format.html { redirect_to @ambiente, notice: 'Ambiente was successfully created.' }
        format.json { render :show, status: :created, location: @ambiente }
      else
        format.html { render :new }
        format.json { render json: @ambiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ambientes/1
  # PATCH/PUT /ambientes/1.json
  def update
    respond_to do |format|
      if @ambiente.update(ambiente_params)
        format.html { redirect_to @ambiente, notice: 'Ambiente was successfully updated.' }
        format.json { render :show, status: :ok, location: @ambiente }
      else
        format.html { render :edit }
        format.json { render json: @ambiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ambientes/1
  # DELETE /ambientes/1.json
  def destroy
    @ambiente.destroy
    respond_to do |format|
      format.html { redirect_to ambientes_url, notice: 'Ambiente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ambiente
      @ambiente = Ambiente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ambiente_params
      params.require(:ambiente).permit(:nome, :descricao)
    end
end

app/controllers/publico/ambientes_controller.rb
class Publico::AmbientesController < ApplicationController
  before_action :set_publico_ambiente, only: [:show, :edit, :update, :destroy]

  # GET /publico/ambientes
  # GET /publico/ambientes.json
  def index
    @publico_ambientes = Publico::Ambiente.all
  end

  # GET /publico/ambientes/1
  # GET /publico/ambientes/1.json
  def show
  end

  # GET /publico/ambientes/new
  def new
    @publico_ambiente = Publico::Ambiente.new
  end

  # GET /publico/ambientes/1/edit
  def edit
  end

  # POST /publico/ambientes
  # POST /publico/ambientes.json
  def create
    @publico_ambiente = Publico::Ambiente.new(publico_ambiente_params)

    respond_to do |format|
      if @publico_ambiente.save
        format.html { redirect_to @publico_ambiente, notice: 'Ambiente was successfully created.' }
        format.json { render :show, status: :created, location: @publico_ambiente }
      else
        format.html { render :new }
        format.json { render json: @publico_ambiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publico/ambientes/1
  # PATCH/PUT /publico/ambientes/1.json
  def update
    respond_to do |format|
      if @publico_ambiente.update(publico_ambiente_params)
        format.html { redirect_to @publico_ambiente, notice: 'Ambiente was successfully updated.' }
        format.json { render :show, status: :ok, location: @publico_ambiente }
      else
        format.html { render :edit }
        format.json { render json: @publico_ambiente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publico/ambientes/1
  # DELETE /publico/ambientes/1.json
  def destroy
    @publico_ambiente.destroy
    respond_to do |format|
      format.html { redirect_to publico_ambientes_url, notice: 'Ambiente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publico_ambiente
      @publico_ambiente = Publico::Ambiente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publico_ambiente_params
      params.require(:publico_ambiente).permit(:nome, :descricao)
    end
end

app/helpers/ambientes_helper.rb
module AmbientesHelper
end

app/helpers/publico/ambientes_helper.rb
module Publico::AmbientesHelper
end

app/views/ambientes/_form.html.erb
<%= form_for(ambiente) do |f| %>
  <% if ambiente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ambiente.errors.count, "error") %> prohibited this ambiente from being saved:</h2>

      <ul>
      <% ambiente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ambientes/edit.html.erb
<h1>Editing Ambiente</h1>

<%= render 'form', ambiente: @ambiente %>

<%= link_to 'Show', @ambiente %> |
<%= link_to 'Back', ambientes_path %>

app/views/ambientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ambientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ambientes.each do |ambiente| %>
      <tr>
        <td><%= ambiente.nome %></td>
        <td><%= ambiente.descricao %></td>
        <td><%= link_to 'Show', ambiente %></td>
        <td><%= link_to 'Edit', edit_ambiente_path(ambiente) %></td>
        <td><%= link_to 'Destroy', ambiente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ambiente', new_ambiente_path %>

app/views/ambientes/new.html.erb
<h1>New Ambiente</h1>

<%= render 'form', ambiente: @ambiente %>

<%= link_to 'Back', ambientes_path %>

app/views/ambientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @ambiente.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @ambiente.descricao %>
</p>

<%= link_to 'Edit', edit_ambiente_path(@ambiente) %> |
<%= link_to 'Back', ambientes_path %>