config/routes.rb
Rails.application.routes.draw do
  resources :avaliacaos
  resources :favoritos
  resources :categoria
  root  'publico/empresas#index'

  namespace :publico do
    resources :clientes
    resources :empresas
    resources :produtos
    resources :ambientes
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/avaliacao.rb
class Avaliacao < ApplicationRecord
end

app/controllers/avaliacaos_controller.rb
class AvaliacaosController < ApplicationController
  before_action :set_avaliacao, only: [:show, :edit, :update, :destroy]

  # GET /avaliacaos
  # GET /avaliacaos.json
  def index
    @avaliacaos = Avaliacao.all
  end

  # GET /avaliacaos/1
  # GET /avaliacaos/1.json
  def show
  end

  # GET /avaliacaos/new
  def new
    @avaliacao = Avaliacao.new
  end

  # GET /avaliacaos/1/edit
  def edit
  end

  # POST /avaliacaos
  # POST /avaliacaos.json
  def create
    @avaliacao = Avaliacao.new(avaliacao_params)

    respond_to do |format|
      if @avaliacao.save
        format.html { redirect_to @avaliacao, notice: 'Avaliacao was successfully created.' }
        format.json { render :show, status: :created, location: @avaliacao }
      else
        format.html { render :new }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avaliacaos/1
  # PATCH/PUT /avaliacaos/1.json
  def update
    respond_to do |format|
      if @avaliacao.update(avaliacao_params)
        format.html { redirect_to @avaliacao, notice: 'Avaliacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @avaliacao }
      else
        format.html { render :edit }
        format.json { render json: @avaliacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaliacaos/1
  # DELETE /avaliacaos/1.json
  def destroy
    @avaliacao.destroy
    respond_to do |format|
      format.html { redirect_to avaliacaos_url, notice: 'Avaliacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avaliacao
      @avaliacao = Avaliacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avaliacao_params
      params.require(:avaliacao).permit(:avaliado_id, :tipo_avaliado, :comentario, :cliente_id)
    end
end

app/helpers/avaliacaos_helper.rb
module AvaliacaosHelper
end

app/views/avaliacaos/_form.html.erb
<%= form_for(avaliacao) do |f| %>
  <% if avaliacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(avaliacao.errors.count, "error") %> prohibited this avaliacao from being saved:</h2>

      <ul>
      <% avaliacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avaliado_id %>
    <%= f.number_field :avaliado_id %>
  </div>

  <div class="field">
    <%= f.label :tipo_avaliado %>
    <%= f.number_field :tipo_avaliado %>
  </div>

  <div class="field">
    <%= f.label :comentario %>
    <%= f.text_area :comentario %>
  </div>

  <div class="field">
    <%= f.label :cliente_id %>
    <%= f.number_field :cliente_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avaliacaos/edit.html.erb
<h1>Editing Avaliacao</h1>

<%= render 'form', avaliacao: @avaliacao %>

<%= link_to 'Show', @avaliacao %> |
<%= link_to 'Back', avaliacaos_path %>

app/views/avaliacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaliacaos</h1>

<table>
  <thead>
    <tr>
      <th>Avaliado</th>
      <th>Tipo avaliado</th>
      <th>Comentario</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avaliacaos.each do |avaliacao| %>
      <tr>
        <td><%= avaliacao.avaliado_id %></td>
        <td><%= avaliacao.tipo_avaliado %></td>
        <td><%= avaliacao.comentario %></td>
        <td><%= avaliacao.cliente_id %></td>
        <td><%= link_to 'Show', avaliacao %></td>
        <td><%= link_to 'Edit', edit_avaliacao_path(avaliacao) %></td>
        <td><%= link_to 'Destroy', avaliacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avaliacao', new_avaliacao_path %>

app/views/avaliacaos/new.html.erb
<h1>New Avaliacao</h1>

<%= render 'form', avaliacao: @avaliacao %>

<%= link_to 'Back', avaliacaos_path %>

app/views/avaliacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Avaliado:</strong>
  <%= @avaliacao.avaliado_id %>
</p>

<p>
  <strong>Tipo avaliado:</strong>
  <%= @avaliacao.tipo_avaliado %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @avaliacao.comentario %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @avaliacao.cliente_id %>
</p>

<%= link_to 'Edit', edit_avaliacao_path(@avaliacao) %> |
<%= link_to 'Back', avaliacaos_path %>